In [1]:
import numpy as np
import torch

In [ ]:
npy_noisy = np.load('../feature/noisy.npy')
npy_clean = np.load('../feature/clean.npy')

In [ ]:
display(npy_noisy.shape)
display(type(npy_noisy))

In [ ]:
torch_noisy = torch.from_numpy(npy_noisy)
torch_clean = torch.from_numpy(npy_clean)

In [ ]:
display(torch_noisy.shape)
display(type(torch_noisy))

In [ ]:
data = torch.stack((torch_noisy,torch_clean),0)

In [ ]:
display(data.shape)

In [ ]:
m = torch.nn.Linear()

# stack

In [13]:
r = torch.rand(3,1)
i = torch.rand(3,1)
print(r)
print(i)
y = torch.stack([r,i],-1)
print(y.shape)
print(y)

tensor([[0.4558],
        [0.7885],
        [0.5707]])
tensor([[0.4299],
        [0.2746],
        [0.0755]])
torch.Size([3, 1, 2])
tensor([[[0.4558, 0.4299]],

        [[0.7885, 0.2746]],

        [[0.5707, 0.0755]]])


# Reshape [B,C,F,T] -> [B,T,F*C]

In [21]:
B = 2
C = 3
F = 4
T = 5
x = torch.rand((B,C,F,T))
print(x.shape)
print(x)
z = torch.reshape(x,(B,C*F,T))
z = z.permute((0,2,1))
print(z.shape)
print(z)

torch.Size([2, 3, 4, 5])
tensor([[[[0.6110, 0.8286, 0.3255, 0.1490, 0.4538],
          [0.4805, 0.4417, 0.8829, 0.2148, 0.0257],
          [0.5246, 0.6687, 0.5311, 0.0602, 0.5969],
          [0.8480, 0.4930, 0.4059, 0.2005, 0.4084]],

         [[0.4185, 0.8744, 0.6209, 0.8529, 0.6595],
          [0.4300, 0.9398, 0.7861, 0.4252, 0.2797],
          [0.6086, 0.0241, 0.5443, 0.0700, 0.8692],
          [0.8467, 0.4646, 0.3098, 0.3242, 0.5100]],

         [[0.0115, 0.0820, 0.9776, 0.1290, 0.2098],
          [0.5951, 0.0589, 0.0427, 0.5044, 0.2110],
          [0.8659, 0.9476, 0.2193, 0.6886, 0.6618],
          [0.2234, 0.2734, 0.6903, 0.8710, 0.6563]]],


        [[[0.1061, 0.9955, 0.5710, 0.5230, 0.9818],
          [0.5171, 0.0823, 0.1672, 0.6300, 0.1782],
          [0.5363, 0.8298, 0.6234, 0.7156, 0.6168],
          [0.8795, 0.5389, 0.4069, 0.0766, 0.6461]],

         [[0.6127, 0.7275, 0.7547, 0.8454, 0.9408],
          [0.6418, 0.7803, 0.2087, 0.2863, 0.9840],
          [0.6079, 0.7119, 0.

# DatasetDCUNET

In [1]:
from dataset.DCUNET import DatasetDCUNET
from utils.hparams import HParam
from model.DCUNET import ModelDCUNET
import torch

/home/kbh/anaconda3/envs/dnn/lib/python3.8/site-packages/torchaudio/backend/utils.py:53: UserWarning: "sox" backend is being deprecated. The default backend will be changed to "sox_io" backend in 0.8.0 and "sox" backend will be removed in 0.9.0. Please migrate to "sox_io" backend. Please refer to https://github.com/pytorch/audio/issues/903 for the detail.
  warnings.warn(


In [21]:
hp = HParam('../config/default.yaml')

In [22]:
data = DatasetDCUNET(hp.data.root+'/STFT_R',hp.data.root+'/WAV',['dt05_bus_simu'],'*.npy',num_frame=hp.model.DCUNET.num_frame)

In [23]:
x= data[0]
print(x['input'].shape)
print(x['clean'].shape)
print(x['noisy'].shape)

torch.Size([3, 513, 80, 2])
torch.Size([20480])
torch.Size([20480])


In [24]:
input = x['input']
# Batch : 1
input =torch.unsqueeze(input,0)
print(input.shape)

torch.Size([1, 3, 513, 80, 2])


In [25]:
model = ModelDCUNET(input_channels=3)

In [26]:
print(input.shape)
output = model(input)

torch.Size([1, 3, 513, 80, 2])
x0 torch.Size([1, 31, 513, 80, 2])
x1 torch.Size([1, 31, 513, 80, 2])
x2 torch.Size([1, 62, 257, 40, 2])
x3 torch.Size([1, 62, 129, 40, 2])
x4 torch.Size([1, 62, 65, 20, 2])
x5 torch.Size([1, 62, 33, 20, 2])
x6 torch.Size([1, 62, 17, 10, 2])
x7 torch.Size([1, 62, 9, 10, 2])
x8 torch.Size([1, 62, 5, 5, 2])
x9 torch.Size([1, 128, 3, 5, 2])
encoded  torch.Size([1, 128, 3, 5, 2])
p0, torch.Size([1, 62, 5, 5, 2]) + x9, torch.Size([1, 62, 5, 5, 2]), padding (2, 1)
p1, torch.Size([1, 62, 9, 10, 2]) + x8, torch.Size([1, 62, 9, 10, 2]), padding (2, 1)
p2, torch.Size([1, 62, 17, 10, 2]) + x7, torch.Size([1, 62, 17, 10, 2]), padding (2, 1)
p3, torch.Size([1, 62, 33, 20, 2]) + x6, torch.Size([1, 62, 33, 20, 2]), padding (2, 1)
p4, torch.Size([1, 62, 65, 20, 2]) + x5, torch.Size([1, 62, 65, 20, 2]), padding (2, 1)
p5, torch.Size([1, 62, 129, 40, 2]) + x4, torch.Size([1, 62, 129, 40, 2]), padding (2, 1)
p6, torch.Size([1, 62, 257, 40, 2]) + x3, torch.Size([1, 62, 257, 

# DatasetFC

+ Magnitude only ? 
+ Respectively ?     
FC => flat  

In [1]:
from dataset.FC import DatasetFC
import torch.nn as nn
from utils.hparams import HParam
import torch
from model.FC import ModelFC

In [2]:
hp = HParam('../config/dnn2_t1.yaml')

In [3]:
data = DatasetFC(hp.data.root+'/STFT_R',['dt05_bus_simu'],'*.npy')

In [4]:
model = ModelFC(hp)

ModelFC[input_size] : 10773


In [5]:
x = data[0]
display(x['input'].shape)
display(x['target'].shape)

torch.Size([10773, 2])

torch.Size([513, 2])

In [6]:
t = torch.unsqueeze(x['input'],0)
display(t.shape)
y = model(t)

torch.Size([1, 10773, 2])

torch.Size([1, 10773])

torch.Size([1, 10773])

In [7]:
display(y.shape)

torch.Size([1, 513, 2])